namespace:
  name: test

replicaCount: 3

image:
  name: nginx
  tag: alpine
  imagePullPolicy: IfNotPresent

resources:
  cpu: 50m
  memory: 256Mi

service:
  port: 8111
  type: ClusterIP

configmap:
  data: "version: alpine"


